### ISSUE TITLE
It would be nice if you could generate a public key from a PEM file

### ISSUE THREAD

**Issue by 93cgutierrez** [c0mm4nd/dart-elliptic#10]
It would be nice if you could generate a public key from a PEM file
thank you
--
I try with final ECPublicKey backendPublicKey = CryptoUtils.ecPublicKeyFromPem(pemString);
but in convertion ECPublicKey(library pointycastle) to PublicKey (library elliptic), I didn't make it

**Comment by c0mm4nd** [comment]
https://github.com/c0mm4nd/dart-ecdsa/issues/3

one PEM is formatted like
```
-----BEGIN PRIVATE KEY-----
<cyphertext>
-----END PRIVATE KEY-----
```

so
```
theRealPrivateKey = PrivateKey.fromDER(decodeBase64(cyphertext))
```

I will add `from/toDER()` method to PrivateKey class in next version.

**Comment by c0mm4nd** [comment]
> I will add `from/toDER()` method to PrivateKey class in next version.

I saw that Google released its PEM library, so I chose to give up implementing a new one or integrating it (for keeping dart-elliptic zero-dep)
In recompense, the PEM operations are written into the README example.
